# Generated by Django 2.0.8 on 2018-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data_pagar',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
