# Generated by Django 2.0.8 on 2018-09-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_conta_data_pagar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='item',
            new_name='item_ref',
        ),
    ]
