# Generated by Django 2.0.8 on 2018-09-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20180924_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='data_pagar',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='item_ref',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='desc',
        ),
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
