# Generated by Django 2.0.8 on 2018-09-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20180924_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='responsavel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
